spring:
  application:
    name: checkout-server
app:
  name: checkout-server
  env: non-prod
server:
  port: 8082
logging:
  level:
    root: DEBUG
    com.shw: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
